context:
  name: cherab-lhd
  version: "0.2.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/munechika-koyo/cherab_lhd/archive/v${{ version }}.tar.gz
  sha256: 4eb52d95b4fc2d0037cd37969a5fe8676840f1ec8c70c09ff4cf98eacf2bd59b

build:
  skip:
    - win
    - match(python, ">3.12")
    - match(python, "<3.10")
  number: 1

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - ninja
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - pkg-config
        - cython
        - numpy
        - cherab
        - if: osx
          then:
            - llvm-openmp
  host:
    - python
    - python-build
    - pip
    - pkg-config
    - meson-python
    - cython
    - numpy
    - cherab
    - if: osx
      then:
        - llvm-openmp
    - if: match(python, "<3.11")
      then:
        - tomli
  run:
    - python
    - scipy
    - matplotlib-base
    - plotly
    - h5py
    - xarray
    - netcdf4
    - rich
    - pooch
    - paramiko
    - tqdm

tests:
  - python:
      imports:
        - cherab.lhd
        - cherab.lhd.emc3
        - cherab.lhd.machine
        - cherab.lhd.observer
        - cherab.lhd.tools
      pip_check: false

  - script:
      - pytest ./tests
    requirements:
      run:
        - pytest
        - pytest-cov
    files:
      source:
        - tests/

about:
  homepage: https://github.com/munechika-koyo/cherab_lhd
  summary: "CHERAB LHD machine-dependent extension"
  description: |
    CHERAB-LHD is the Large Helical Device (LHD) machine-dependent extensions of cherab code.
    LHD is a helical magnetic confinement fusion device in the National Institute for Fusion Science (NIFS) in Japan.
  license: BSD-3-Clause
  license_file: LICENSE.md
  documentation: https://cherab-lhd.readthedocs.io/
  repository: https://github.com/munechika-koyo/cherab_lhd

extra:
  recipe-maintainers:
    - munechika-koyo
